### ISSUE TITLE
Head Hunter model has wrong Stat Line

### ISSUE THREAD

**Issue by BenMitchell1979** [greeny88/Freeblades-Freeband-Builder#13]
{        "factions": ["Black Rose Bandits", "Black Thorn Bandits"],        "name": "Head Hunter",        "displayName": "Head Hunter",        "stats": {            "abilities": {                "dexterity": 10,                "strength": 10            },            "discipline": 10,            "type": "Hero",            "talents": ["Amphibious", "Furious", "Tough", "Bloodstruck"],            "speed": 6,            "melee": [{                "name": "Falchion",                "rating": 10,                "damage": 8,                "damageBonus": 1            }],            "armor": 4        },        "type": "Standard",        "value": 25,        "gender": "M",        "race": "Shakrim"    },

Need to replace Dexterity: 10 to Endurance: 10 so that Head Hunter shows correct LP value of 4

**Comment by BenMitchell1979** [comment]
I was going to fix this and submit a PR. But looks like you don't allow any idiot to branch and PR :)

**Comment by greeny88** [comment]
Branches have been updated with the correct stat line. The headhunter was also missing the Shakrim faction in it's list and I updated the name to be closer to what is in the LRB.

The site has been updated with these changes.
